### ISSUE TITLE
Custom emoji reactions causes an error

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#36]
Problem is with `karma.py` module.
```
Traceback (most recent call last):
  File "/home/emerald/.local/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 37, in on_reaction_add
    await bot_module.on_reaction_add(reaction, client, user)
  File "/home/emerald/scubot/modules/karma.py", line 39, in on_reaction_add
    if reaction.emoji in self.reaction_emojis or reaction.emoji.name in self.reaction_emojis:
AttributeError: 'str' object has no attribute 'name'
```

**Comment by QuickRecon** [comment]
Fixed with e1b10e8278b019063612d1f9ade1c7807023cbf3
