### ISSUE TITLE
Role assignment crashes bot

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#43]
```
Traceback (most recent call last):
  File "redacted/python3.5/site-packages/discord.client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line, 29, in _on_message
    await bot_module.parse_command(message, client)
  File "redacted/scubot/modules/roles.py", line 28, in parse_command
    role_to_assign = message.server.roles[role[0]]
IndexError: list index out of range
```

I cannot reproduce this error by sending non-existent roles or an otherwise invalid command, but it happens once in a while and the bot will crash because of it.

**Comment by QuickRecon** [comment]
No longer issue afaik, tagging as wontfix and closing.
